# Generated by Django 3.1.3 on 2021-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210106_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
