# Generated by Django 3.1.3 on 2021-01-07 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_auto_20210106_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
