# Generated by Django 3.1.4 on 2021-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210107_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(default='https://unmpress.com/sites/default/files/default_images/no_image_book.jpg', null=True),
        ),
    ]
